const Sequelize = require('sequelize');
const env = process.env.NODE_ENV || 'development';
const config = require('../config/config')[env];
const User = require('./user');
const Study = require('./study');
const Admin = require('./admin');
const Alarm = require('./alarm');
const Apply = require('./apply');
const Character = require('./character');
const Evaluation = require('./evaluation');
const Gu = require('./gu');
const Image = require('./image');
const Interest = require('./interest');
const Notice = require('./notice');
const Quit = require('./quit');
const Region = require('./region');
const Report = require('./report');
const State = require('./state');
const Terms = require('./terms');
const studyMember = require('./studyMember');
const Search = require('./search');

const db = {};
const sequelize = new Sequelize(config.database, config.username, config.password, config);

db.sequelize = sequelize;
db.User = User;
db.Study = Study;
db.Admin = Admin;
db.Alarm = Alarm;
db.Apply = Apply;
db.Character = Character;
db.Evaluation = Evaluation;
db.Gu = Gu;
db.Image = Image;
db.Interest = Interest;
db.Notice = Notice;
db.Quit = Quit;
db.Region = Region;
db.Report = Report;
db.State = State;
db.Study = Study;
db.Terms = Terms;
db.studyMember = studyMember;
db.Search = Search;

User.init(sequelize);
Study.init(sequelize);
Admin.init(sequelize);
Alarm.init(sequelize);
Apply.init(sequelize);
Character.init(sequelize);
Evaluation.init(sequelize);
Gu.init(sequelize);
Image.init(sequelize);
Interest.init(sequelize);
Notice.init(sequelize);
Quit.init(sequelize);
Region.init(sequelize);
Report.init(sequelize);
State.init(sequelize);
Terms.init(sequelize);
studyMember.init(sequelize);
Search.init(sequelize);

User.associate(db);
Study.associate(db);
Alarm.associate(db);
Evaluation.associate(db);
Gu.associate(db);
Image.associate(db);
Region.associate(db);
Report.associate(db);
Apply.associate(db);
State.associate(db);
Search.associate(db);
Interest.associate(db);
Character.associate(db);

module.exports = db;
